### ISSUE TITLE
files里缺少这些安装文件

### ISSUE THREAD

**Issue by lvelvis** [cloudfirst/promansible-Install#1]
- promansible-monitor_1.1_all.deb
     - promansible-daemon_1.1_all.deb
     - promansible-wtee_1.1_all.deb
     - prometheus-server_1.1_all.deb
     - alertman-server_1.1_all.deb
     - grafana-server_1.1_all.deb
     - snmp-exporter_1.1_all.deb
     - node-exporter_1.1_all.deb

**Comment by aiyandaodi** [comment]
When I execute the installation of promansible-monitor，The following error occurred:
failed: [monitor] => (item=promansible-monitor_1.1_all.deb) => {"failed": true, "item": "promansible-monitor_1.1_all.deb", "msg": "dpkg --force-confdef --force-confold -i /tmp/promansible-monitor_1.1_all.deb failed", "stderr": "apache2: no process found\nTraceback (most recent call last):\n  File \"manage.py\", line 22, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py\", line 363, in execute_from_command_line\n    utility.execute()\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py\", line 355, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/base.py\", line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/base.py\", line 327, in execute\n    self.check()\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/base.py\", line 359, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py\", line 61, in _run_checks\n    issues = run_checks(tags=[Tags.database])\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/usr/local/lib/python2.7/dist-packages/django/core/checks/database.py\", line 10, in check_database_backends\n    issues.extend(conn.validation.check(**kwargs))\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py\", line 9, in check\n    issues.extend(self._check_sql_mode(**kwargs))\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py\", line 13, in _check_sql_mode\n    with self.connection.cursor() as cursor:\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py\", line 254, in cursor\n    return self._cursor()\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py\", line 229, in _cursor\n    self.ensure_connection()\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py\", line 213, in ensure_connection\n    self.connect()\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/utils.py\", line 94, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py\", line 213, in ensure_connection\n    self.connect()\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py\", line 189, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File \"/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py\", line 274, in get_new_connection\n    conn = Database.connect(**conn_params)\n  File \"/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py\", line 86, in Connect\n    return Connection(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py\", line 204, in __init__\n    super(Connection, self).__init__(*args, **kwargs2)\ndjango.db.utils.OperationalError: (2002, \"Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\")\ndpkg: error processing package promansible-monitor (--install):\n subprocess installed post-installation script returned error exit status 1\nErrors were encountered while processing:\n promansible-monitor\n", "stdout": "Selecting previously unselected package promansible-monitor.\n(Reading database ... 29860 files and directories currently installed.)\nPreparing to unpack .../promansible-monitor_1.1_all.deb ...\nUnpacking promansible-monitor (1.1) ...\nSetting up promansible-monitor (1.1) ...\nProcessing /usr/local/webconfig/pip/Django-1.11.3.tar.gz\nProcessing /usr/local/webconfig/pip/mysqlclient-1.3.10.tar.gz\nProcessing /usr/local/webconfig/pip/netifaces-0.10.6.tar.gz\nProcessing /usr/local/webconfig/pip/python-memcached-1.58.tar.gz\nProcessing /usr/local/webconfig/pip/pyzmq-13.1.0.tar.gz\nRequirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django==1.11.3) (2018.5)\nRequirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/dist-packages (from python-memcached==1.58) (1.10.0)\nBuilding wheels for collected packages: Django, mysqlclient, netifaces, python-memcached, pyzmq\n  Running setup.py bdist_wheel for Django: started\n  Running setup.py bdist_wheel for Django: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/a4/a1/81/b23ce79005893c540d77eddb12939a708be9a225fc10a0fdba\n  Running setup.py bdist_wheel for mysqlclient: started\n  Running setup.py bdist_wheel for mysqlclient: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/f3/08/04/4b42b364fb496a8c22b4046cc3aa34ab65245378959c7a9a7a\n  Running setup.py bdist_wheel for netifaces: started\n  Running setup.py bdist_wheel for netifaces: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/04/68/9c/d027cfb4fd80906782e74324ad083e6a19a1458bf0be7f1e6b\n  Running setup.py bdist_wheel for python-memcached: started\n  Running setup.py bdist_wheel for python-memcached: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/b2/0f/94/222787a72427b4aa4fa6978d368fadb95d77b55a21811996f6\n  Running setup.py bdist_wheel for pyzmq: started\n  Running setup.py bdist_wheel for pyzmq: finished with status 'done'\n  Stored in directory: /root/.cache/pip/wheels/43/18/16/164e304302cb5f443d23b14868b39e9b2c19cbdac815fd5a13\nSuccessfully built Django mysqlclient netifaces python-memcached pyzmq\nInstalling collected packages: Django, mysqlclient, netifaces, python-memcached, pyzmq\n  Found existing installation: pyzmq 17.1.0\n    Uninstalling pyzmq-17.1.0:\n      Successfully uninstalled pyzmq-17.1.0\nSuccessfully installed Django-1.11.3 mysqlclient-1.3.10 netifaces-0.10.6 python-memcached-1.58 pyzmq-13.1.0\nSite 000-default disabled.\nTo activate the new configuration, you need to run:\n  service apache2 reload\nEnabling site wsgi.\nTo activate the new configuration, you need to run:\n  service apache2 reload\n * Starting Apache httpd web server apache2\n * \nFile doesnt exists\n", "stdout_lines": ["Selecting previously unselected package promansible-monitor.", "(Reading database ... 29860 files and directories currently installed.)", "Preparing to unpack .../promansible-monitor_1.1_all.deb ...", "Unpacking promansible-monitor (1.1) ...", "Setting up promansible-monitor (1.1) ...", "Processing /usr/local/webconfig/pip/Django-1.11.3.tar.gz", "Processing /usr/local/webconfig/pip/mysqlclient-1.3.10.tar.gz", "Processing /usr/local/webconfig/pip/netifaces-0.10.6.tar.gz", "Processing /usr/local/webconfig/pip/python-memcached-1.58.tar.gz", "Processing /usr/local/webconfig/pip/pyzmq-13.1.0.tar.gz", "Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django==1.11.3) (2018.5)", "Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/dist-packages (from python-memcached==1.58) (1.10.0)", "Building wheels for collected packages: Django, mysqlclient, netifaces, python-memcached, pyzmq", "  Running setup.py bdist_wheel for Django: started", "  Running setup.py bdist_wheel for Django: finished with status 'done'", "  Stored in directory: /root/.cache/pip/wheels/a4/a1/81/b23ce79005893c540d77eddb12939a708be9a225fc10a0fdba", "  Running setup.py bdist_wheel for mysqlclient: started", "  Running setup.py bdist_wheel for mysqlclient: finished with status 'done'", "  Stored in directory: /root/.cache/pip/wheels/f3/08/04/4b42b364fb496a8c22b4046cc3aa34ab65245378959c7a9a7a", "  Running setup.py bdist_wheel for netifaces: started", "  Running setup.py bdist_wheel for netifaces: finished with status 'done'", "  Stored in directory: /root/.cache/pip/wheels/04/68/9c/d027cfb4fd80906782e74324ad083e6a19a1458bf0be7f1e6b", "  Running setup.py bdist_wheel for python-memcached: started", "  Running setup.py bdist_wheel for python-memcached: finished with status 'done'", "  Stored in directory: /root/.cache/pip/wheels/b2/0f/94/222787a72427b4aa4fa6978d368fadb95d77b55a21811996f6", "  Running setup.py bdist_wheel for pyzmq: started", "  Running setup.py bdist_wheel for pyzmq: finished with status 'done'", "  Stored in directory: /root/.cache/pip/wheels/43/18/16/164e304302cb5f443d23b14868b39e9b2c19cbdac815fd5a13", "Successfully built Django mysqlclient netifaces python-memcached pyzmq", "Installing collected packages: Django, mysqlclient, netifaces, python-memcached, pyzmq", "  Found existing installation: pyzmq 17.1.0", "    Uninstalling pyzmq-17.1.0:", "      Successfully uninstalled pyzmq-17.1.0", "Successfully installed Django-1.11.3 mysqlclient-1.3.10 netifaces-0.10.6 python-memcached-1.58 pyzmq-13.1.0", "Site 000-default disabled.", "To activate the new configuration, you need to run:", "  service apache2 reload", "Enabling site wsgi.", "To activate the new configuration, you need to run:", "  service apache2 reload", " * Starting Apache httpd web server apache2", " * ", "File doesnt exists"]}
failed: [monitor] => (item=promansible-daemon_1.1_all.deb) => {"failed": true, "item": "promansible-daemon_1.1_all.deb", "msg": "dpkg --force-confdef --force-confold -i /tmp/promansible-daemon_1.1_all.deb failed", "stderr": "dpkg: dependency problems prevent configuration of promansible-daemon:\n promansible-daemon depends on promansible-monitor; however:\n  Package promansible-monitor is not configured yet.\n\ndpkg: error processing package promansible-daemon (--install):\n dependency problems - leaving unconfigured\nErrors were encountered while processing:\n promansible-daemon\n", "stdout": "Selecting previously unselected package promansible-daemon.\n(Reading database ... 31168 files and directories currently installed.)\nPreparing to unpack .../promansible-daemon_1.1_all.deb ...\nUnpacking promansible-daemon (1.1) ...\n", "stdout_lines": ["Selecting previously unselected package promansible-daemon.", "(Reading database ... 31168 files and directories currently installed.)", "Preparing to unpack .../promansible-daemon_1.1_all.deb ...", "Unpacking promansible-daemon (1.1) ..."]}

**Comment by aiyandaodi** [comment]
When I execute dpkg --force-confdef --force-confold -i /tmp/promansible-monitor_1.1_all.deb，The following error occurred:
(Reading database ... 35119 files and directories currently installed.)
Preparing to unpack .../promansible-monitor_1.1_all.deb ...
Unpacking promansible-monitor (1.1) over (1.1) ...
Setting up promansible-monitor (1.1) ...
Processing /usr/local/webconfig/pip/Django-1.11.3.tar.gz
Processing /usr/local/webconfig/pip/mysqlclient-1.3.10.tar.gz
Processing /usr/local/webconfig/pip/netifaces-0.10.6.tar.gz
Processing /usr/local/webconfig/pip/python-memcached-1.58.tar.gz
Processing /usr/local/webconfig/pip/pyzmq-13.1.0.tar.gz
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django==1.11.3) (2018.5)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/dist-packages (from python-memcached==1.58) (1.10.0)
Building wheels for collected packages: Django, mysqlclient, netifaces, python-memcached, pyzmq
  Running setup.py bdist_wheel for Django ... done
  Stored in directory: /home/luhya/.cache/pip/wheels/a4/a1/81/b23ce79005893c540d77eddb12939a708be9a225fc10a0fdba
  Running setup.py bdist_wheel for mysqlclient ... done
  Stored in directory: /home/luhya/.cache/pip/wheels/f3/08/04/4b42b364fb496a8c22b4046cc3aa34ab65245378959c7a9a7a
  Running setup.py bdist_wheel for netifaces ... done
  Stored in directory: /home/luhya/.cache/pip/wheels/04/68/9c/d027cfb4fd80906782e74324ad083e6a19a1458bf0be7f1e6b
  Running setup.py bdist_wheel for python-memcached ... done
  Stored in directory: /home/luhya/.cache/pip/wheels/b2/0f/94/222787a72427b4aa4fa6978d368fadb95d77b55a21811996f6
  Running setup.py bdist_wheel for pyzmq ... done
  Stored in directory: /home/luhya/.cache/pip/wheels/43/18/16/164e304302cb5f443d23b14868b39e9b2c19cbdac815fd5a13
Successfully built Django mysqlclient netifaces python-memcached pyzmq
Installing collected packages: Django, mysqlclient, netifaces, python-memcached, pyzmq
  Found existing installation: Django 1.11.3
    Uninstalling Django-1.11.3:
      Successfully uninstalled Django-1.11.3
  Found existing installation: mysqlclient 1.3.10
    Uninstalling mysqlclient-1.3.10:
      Successfully uninstalled mysqlclient-1.3.10
  Found existing installation: netifaces 0.10.6
    Uninstalling netifaces-0.10.6:
      Successfully uninstalled netifaces-0.10.6
  Found existing installation: python-memcached 1.58
    Uninstalling python-memcached-1.58:
      Successfully uninstalled python-memcached-1.58
  Found existing installation: pyzmq 13.1.0
    Uninstalling pyzmq-13.1.0:
      Successfully uninstalled pyzmq-13.1.0
Successfully installed Django-1.11.3 mysqlclient-1.3.10 netifaces-0.10.6 python-memcached-1.58 pyzmq-13.1.0
Site 000-default already disabled
Site wsgi already enabled
 * Starting Apache httpd web server apache2                                      * 
File exists
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 61, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
dpkg: error processing package promansible-monitor (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 promansible-monitor

**Comment by fanjianfeifei** [comment]
TASK [monitor : copy monitor's deb package to target host] ***********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/home/luhya/src/promansible-Install/playbook/promansible-monitor_1.1_all.deb
failed: [monitor] (item=promansible-monitor_1.1_all.deb) => {"changed": false, "item": "promansible-monitor_1.1_all.deb", "msg": "Could not find or access 'promansible-monitor_1.1_all.deb'\nSearched in:\n\t/home/luhya/src/promansible-Install/playbook/roles/monitor/files/promansible-monitor_1.1_all.deb\n\t/home/luhya/src/promansible-Install/playbook/roles/monitor/promansible-monitor_1.1_all.deb\n\t/home/luhya/src/promansible-Install/playbook/roles/monitor/tasks/files/promansible-monitor_1.1_all.deb\n\t/home/luhya/src/promansible-Install/playbook/roles/monitor/tasks/promansible-monitor_1.1_all.deb\n\t/home/luhya/src/promansible-Install/playbook/files/promansible-monitor_1.1_all.deb\n\t/home/luhya/src/promansible-Install/playbook/promansible-monitor_1.1_all.deb"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: 	/home/luhya/src/promansible-Install/playbook/promansible-daemon_1.1_all.deb

**Comment by fanjianfeifei** [comment]
> * promansible-monitor_1.1_all.deb
>   
>   * promansible-daemon_1.1_all.deb
>   * promansible-wtee_1.1_all.deb
>   * prometheus-server_1.1_all.deb
>   * alertman-server_1.1_all.deb
>   * grafana-server_1.1_all.deb
>   * snmp-exporter_1.1_all.deb
>   * node-exporter_1.1_all.deb
Has it been solved
